image: atlassian/default-image:latest

pipelines:
  default: 
      - step:
          name: Build
          caches:
            - maven
          script: # Modify the commands below to build your repository.
            #- apt-get update
            - mvn -B -s settings.xml deploy -Dmaven.test.skip=true # -B batch mode makes Maven less verbose
  branches: 
    master: 
      - step:
          name: Build
          caches:
            - maven
          script: # Modify the commands below to build your repository.
            #- apt-get update
            - mkdir -p dist/
            - mvn -B -s settings.xml deploy # -B batch mode makes Maven less verbose
            - mv vo-distribution/target/vo-distribution-beanstalk-app-zip.zip dist/distribution-beanstalk-app-zip.zip
          artifacts: 
            - dist/**
      - step:
          name: Deploy To Test Environment
          image: python:3.5.1
          deployment: test
          script: # Modify the commands below to build your repository.
            #- apt-get install -y python-pip
            - pip install boto3==1.3.0
            - python beanstalk_deploy.py   
